"""j\

Revision ID: 23ed42844608
Revises: 0ec7a5023051
Create Date: 2025-11-28 04:45:40.520467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ed42844608'
down_revision = '0ec7a5023051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnic_image', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('selfie_image', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('renter_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('safety_rules_agreed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('agreement_signed_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('note',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'chat', ['chat_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('note',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('agreement_signed_at')
        batch_op.drop_column('safety_rules_agreed')
        batch_op.drop_column('renter_verified')
        batch_op.drop_column('selfie_image')
        batch_op.drop_column('cnic_image')

    # ### end Alembic commands ###
