"""ok

Revision ID: 381e9a77d71d
Revises: f90ac1d50b1e
Create Date: 2025-12-03 15:19:01.967832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381e9a77d71d'
down_revision = 'f90ac1d50b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_blocked')

    # ### end Alembic commands ###
