"""ok

Revision ID: 5337b21c8ca1
Revises: b7db71ebacfa
Create Date: 2025-12-04 16:18:20.926410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5337b21c8ca1'
down_revision = 'b7db71ebacfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
