"""nh

Revision ID: 5e4c27c33efc
Revises: 891ed1f2bc9e
Create Date: 2025-11-28 05:38:18.777984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e4c27c33efc'
down_revision = '891ed1f2bc9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_rented', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_available')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_rented')

    # ### end Alembic commands ###
