"""ok

Revision ID: 891ed1f2bc9e
Revises: 9d7cbdb8db32
Create Date: 2025-11-28 05:35:49.393186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891ed1f2bc9e'
down_revision = '9d7cbdb8db32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('is_available')

    # ### end Alembic commands ###
