"""n

Revision ID: 930bd0f61546
Revises: 75a11c07f4a4
Create Date: 2025-11-27 06:09:11.798676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '930bd0f61546'
down_revision = '75a11c07f4a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listing_image')
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', postgresql.JSON(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_column('images')

    op.create_table('listing_image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], name=op.f('listing_image_listing_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('listing_image_pkey'))
    )
    # ### end Alembic commands ###
