"""k

Revision ID: 9d7cbdb8db32
Revises: c780e16d97b5
Create Date: 2025-11-28 05:10:41.836190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d7cbdb8db32'
down_revision = 'c780e16d97b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_request', schema=None) as batch_op:
        batch_op.drop_column('rider_note')
        batch_op.drop_column('payment_proof')
        batch_op.drop_column('payment_verified')
        batch_op.drop_column('payment_details_sent_at')
        batch_op.drop_column('rider_phone')
        batch_op.drop_column('payment_submitted_at')
        batch_op.drop_column('rider_name')
        batch_op.drop_column('payment_transaction_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_transaction_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rider_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rider_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_details_sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_proof', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rider_note', sa.VARCHAR(length=300), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
