"""ök

Revision ID: b40caa212ed1
Revises: 44dcf53e9012
Create Date: 2025-11-27 19:31:36.679415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b40caa212ed1'
down_revision = '44dcf53e9012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user1_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user2_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('chat_user2_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('chat_user1_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user1_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user2_id'], ['id'])
        batch_op.drop_column('user2')
        batch_op.drop_column('user1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user1', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user2', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chat_user1_fkey'), 'user', ['user1'], ['id'])
        batch_op.create_foreign_key(batch_op.f('chat_user2_fkey'), 'user', ['user2'], ['id'])
        batch_op.drop_column('user2_id')
        batch_op.drop_column('user1_id')

    # ### end Alembic commands ###
