"""ok

Revision ID: b7db71ebacfa
Revises: 1de645c92696
Create Date: 2025-12-04 15:46:28.085977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7db71ebacfa'
down_revision = '1de645c92696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fcm_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fcm_token', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('audio_url')

    # ### end Alembic commands ###
