"""ok

Revision ID: c780e16d97b5
Revises: 23ed42844608
Create Date: 2025-11-28 05:05:05.816625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c780e16d97b5'
down_revision = '23ed42844608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renter_delivery_address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('renter_delivery_contact', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('renter_delivery_note', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('owner_pickup_address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('owner_pickup_contact', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('owner_pickup_note', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('owner_payment_bank', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('owner_payment_title', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('owner_payment_account', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('owner_payment_note', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('payment_details_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payment_proof', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('payment_transaction_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('payment_submitted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payment_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rider_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('rider_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rider_note', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rental_request', schema=None) as batch_op:
        batch_op.drop_column('rider_note')
        batch_op.drop_column('rider_phone')
        batch_op.drop_column('rider_name')
        batch_op.drop_column('payment_verified')
        batch_op.drop_column('payment_submitted_at')
        batch_op.drop_column('payment_transaction_id')
        batch_op.drop_column('payment_proof')
        batch_op.drop_column('payment_details_sent_at')
        batch_op.drop_column('owner_payment_note')
        batch_op.drop_column('owner_payment_account')
        batch_op.drop_column('owner_payment_title')
        batch_op.drop_column('owner_payment_bank')
        batch_op.drop_column('owner_pickup_note')
        batch_op.drop_column('owner_pickup_contact')
        batch_op.drop_column('owner_pickup_address')
        batch_op.drop_column('renter_delivery_note')
        batch_op.drop_column('renter_delivery_contact')
        batch_op.drop_column('renter_delivery_address')

    # ### end Alembic commands ###
