"""ok

Revision ID: f90ac1d50b1e
Revises: a7a0b7e863d4
Create Date: 2025-12-03 03:45:44.777496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f90ac1d50b1e'
down_revision = 'a7a0b7e863d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_banner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('bg_color', sa.String(length=30), nullable=True),
    sa.Column('text_color', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_banner')
    # ### end Alembic commands ###
